site_name: Huma
site_url: https://huma.rocks
copyright: Copyright &copy; 2020-2024 Daniel G. Taylor. Logo &amp; branding designed by Kari Taylor.
repo_name: danielgtaylor/huma
repo_url: https://github.com/danielgtaylor/huma
edit_uri: edit/main/docs/docs/
nav:
  - Home: index.md
  - "Why Huma":
      - "Why Huma": why/index.md
      - "What About Design-First?": why/what-about-design-first.md
      - "Benchmarks": why/benchmarks.md
  - "Tutorial":
      - "Get Started":
          - "Installation": tutorial/installation.md
          - "Your First API": tutorial/your-first-api.md
      - "Level Up":
          - "Service Config": tutorial/service-configuration.md
          - "Sending Data": tutorial/sending-data.md
          - "Writing Tests": tutorial/writing-tests.md
          - "CLI Client": tutorial/cli-client.md
          - "Client SDKs": tutorial/client-sdks.md
  - "Features":
      - "Features Overview": features/index.md
      - "The Server":
          - "Bring Your Own Router": features/bring-your-own-router.md
          - "Middleware": features/middleware.md
          - "Service CLI": features/cli.md
      - "OpenAPI & JSON Schema":
          - "Config & OpenAPI": features/openapi-generation.md
          - "Generated API Docs": features/api-docs.md
          - "JSON Schema & Registry": features/json-schema-registry.md
          - "Schema Customization": features/schema-customization.md
          - "Model Validation": features/model-validation.md
      - "Operations":
          - "Operations": features/operations.md
          - "Groups": features/groups.md
          - "Requests":
              - "Request Inputs": features/request-inputs.md
              - "Validation": features/request-validation.md
              - "Resolvers": features/request-resolvers.md
              - "Limits": features/request-limits.md
          - "Responses":
              - "Response Outputs": features/response-outputs.md
              - "Response Errors": features/response-errors.md
              - "Serialization": features/response-serialization.md
              - "Streaming": features/response-streaming.md
              - "Transformers": features/response-transformers.md
      - "Extra Packages":
          - "Auto PATCH Operations": features/auto-patch.md
          - "Conditional Requests": features/conditional-requests.md
          - "Server Sent Events (SSE)": features/server-sent-events-sse.md
          - "Test Utilities": features/test-utilities.md
      - "Clients":
          - "CLI AutoConfig": features/cli-auto-config.md
  - "How To Guides":
      - "Conditional Fields": how-to/conditional-fields.md
      - "Custom Validation": how-to/custom-validation.md
      - "Image Response": how-to/image-response.md
      - "Graceful Shutdown": how-to/graceful-shutdown.md
      - "Migrating From V1": how-to/migrate.md
      - "OAuth 2.0 & JWT": how-to/oauth2-jwt.md
  - "Go Reference": "https://pkg.go.dev/github.com/danielgtaylor/huma/v2?tab=doc"
theme:
  name: material
  custom_dir: overrides
  logo: logo.png
  favicon: favicon.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: blue
      accent: custom

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: black
      accent: custom
  features:
    - content.action.edit
    - content.code.copy
    # - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/danielgtaylor/huma
  analytics:
    provider: google
    property: G-YCZGGQHTX1
extra_css:
  - stylesheets/asciinema-player.css
  - stylesheets/extra.css
extra_javascript:
  - scripts/asciinema-player.min.js
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search
  - macros
  - social
  - tags
